### ISSUE TITLE
HSPsquared model created from ./tests/ZRW_WestIndian/HSPF.uci fails with KeyError

### ISSUE THREAD

**Issue by timcera** [respec/HSPsquared#179]
`hsp2 import_uci ./tests/ZRW_WestIndian/HSPF.uci ./tests/ZRW_WestIndian/ref_run_HSPF.h5`
`hsp2 run ./tests/ZRW_WestIndian/ref_run_HSPF.h5`

fails with the error:

```
2024-10-02 22:47:31.65   Processing started for file ./tests/ZRW_WestIndian/ref_run_HSPF.h5; saveall=True
Traceback (most recent call last):
  File "/var/home/timcera/miniconda3/envs/default311/bin/hsp2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/HSP2_CLI.py", line 9, in main
    cltoolbox.main()
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 323, in __call__
    return self.execute(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 319, in execute
    return command(*real_args)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/commands.py", line 26, in run
    main(io_manager, saveall=saveall, jupyterlab=compress)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/main.py", line 119, in main
    state_om_model_run_prep(state, io_manager, siminfo)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om.py", line 206, in state_om_model_run_prep
    model_loader_recursive(state["model_data"], model_root_object)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om.py", line 416, in model_loader_recursive
    model_object = model_class_loader(object_name, model_props, container)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om.py", line 336, in model_class_loader
    model_object = SpecialAction(
                   ^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om_special_action.py", line 23, in __init__
    super().__init__(name, container, model_props)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om_model_object.py", line 87, in __init__
    self.parse_model_props(model_props)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om_special_action.py", line 62, in parse_model_props
    domain = self.state["model_object_cache"][
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/STATE/RCHRES_R110'
```

**Comment by rburghol** [comment]
Hey @timcera I am getting back to this.  This happens because the state gets populated with all the `operation` x `segment` combinations, and due to the structure of this UCI, there are a whole bunch of reaches that exist, but are not in the operations.  Clearly this is solvable, I am thinking that rather than just iterate through stuff in the `OPN SEQUENCE` block I need to insure that anything in the various `GEN-INFO` tables gets populated, so:
- `/IMPLND/GENERAL/INFO`
- `/PERLND/GENERAL/INFO`
- `/RCHRES/GENERAL/INFO`

While these tables ARE imported from UCI to hdf5, from what I can tell, they are NOT brought into the `parameter` object at runtime, or rather, they are brought in all under the `model` object.  Note sure if your UCI parser handles that, or adds that to the import.  

Am I on the right track? And, as I am unused to this kind of setup in HSPF, are you able to give me any insight into this king of structure? Thanks!

**Comment by rburghol** [comment]
This was the wrong approach. ~~@timcera - this error is now resolved. However, while SPEC-ACTIONS/STATE no longer fail with this case, the test model `ZRW_WestIndian` does not run to completion.  I have not dug too deeply into this, but I question that if it **IS** valid HSPF to have something in a `GEN-INFO` block that does not appear in the `OPN SEQUENCE` which is what caused the error in this issue (see PR #222 for details on the fix).  ~~

Subsequently, the errors I got with a cursory examination are as follows:
- Running with `numba` enabled, `hsp2 run ./tests/ZRW_WestIndian/ref_run_HSPF.h5` yields:
```
2026-02-05 18:57:37.70   Processing started for file ./tests/ZRW_WestIndian/ref_run_HSPF.h5; saveall=True
Skipping un-typed siminfo
op_tokens has 4357 elements, with  73 executable elements
2026-02-05 18:57:54.34   Simulation Start: 1995-01-01 00:00:00, Stop: 2018-12-31 22:00:00
2026-02-05 18:57:54.34      PERLND P005 DELT(minutes): 60
2026-02-05 18:57:55.34         ATEMP
2026-02-05 18:57:56.90         SNOW
2026-02-05 18:57:59.01         PWATER
Traceback (most recent call last):
  File "/usr/local/share/venv/p39test/bin/hsp2", line 7, in <module>
    sys.exit(main())
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2tools/HSP2_CLI.py", line 10, in main
    cltoolbox.main()
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/cltoolbox/cltoolbox.py", line 422, in __call__
    return self.execute(sys.argv[1:])
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/cltoolbox/cltoolbox.py", line 418, in execute
    return command(*real_args)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2tools/commands.py", line 26, in run
    main(io_manager, saveall=saveall, jupyterlab=compress)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2/main.py", line 409, in main
    errors, errmessages = function(io_manager, siminfo, ui, ts)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2/PWATER.py", line 104, in pwater
    errors = _pwater_(ui, ts)  # traditional HSPF HPERWAT
ZeroDivisionError: division by zero
```
- Running with `numba` disabled actually crashes sooner (maybe a diff btwn python and numba and not a real error?):
```
NUMBA_DISABLE_JIT=1 hsp2 run ./tests/ZRW_WestIndian/ref_run_HSPF.h5
2026-02-05 18:58:17.55   Processing started for file ./tests/ZRW_WestIndian/ref_run_HSPF.h5; saveall=True
Skipping un-typed siminfo
op_tokens has 4357 elements, with  73 executable elements
2026-02-05 18:58:25.94   Simulation Start: 1995-01-01 00:00:00, Stop: 2018-12-31 22:00:00
2026-02-05 18:58:25.94      PERLND P005 DELT(minutes): 60
2026-02-05 18:58:26.14         ATEMP
Traceback (most recent call last):
  File "/usr/local/share/venv/p39test/bin/hsp2", line 7, in <module>
    sys.exit(main())
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2tools/HSP2_CLI.py", line 10, in main
    cltoolbox.main()
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/cltoolbox/cltoolbox.py", line 422, in __call__
    return self.execute(sys.argv[1:])
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/cltoolbox/cltoolbox.py", line 418, in execute
    return command(*real_args)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2tools/commands.py", line 26, in run
    main(io_manager, saveall=saveall, jupyterlab=compress)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2/main.py", line 409, in main
    errors, errmessages = function(io_manager, siminfo, ui, ts)
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2/ATEMP.py", line 26, in atemp
    errors = _atemp_(ui, ts)  # run ATEMP_ simulation code
  File "/usr/local/share/venv/p39test/lib/python3.9/site-packages/hsp2/hsp2/ATEMP.py", line 56, in _atemp_
    lapse = 0.0035 if PREC[step] > k else LAPSE[step]  # use wet lapse if prec
```

**Comment by rburghol** [comment]
@timcera -- note this is due to the special actions engine NOT screening for `SPEC-ACTIONS` that are appearing in the UCI, but whose spource data (like `RCHRES` where they get a value) are NOT enabled via the `OP SEQUENCE` block.  I will update with progress here when I get the code set to not enable these actions if their source segments are disabled.

**Comment by timcera** [comment]
You can't refer to something in `SPEC-ACTIONS` that isn't in `OP SEQUENCE` block.  `SPEC-ACTIONS` is special that way.  For a "regular" parameter table for example /RCHRES/HYDR/PARAMETERS you can have parameters for R001, R002, R003, ..., R999 and HSPF only uses the parameters for the RCHRESes in the `OP SEQUENCE` block.

**Comment by timcera** [comment]
HSPF will fail if there is a reference in `SPEC-ACTIONS` that isn't in `OP SEQUENCE`.  I think that would be fine for HSP2.

**Comment by rburghol** [comment]
Ahh ok thanks!-- so I should just make this an explicit test for this in the model prep step, throw an exception giving a detailed notification to the user. 

fpath="./tests/ZRW_WestIndian/ref_run_HSPF.h5"

**Comment by timcera** [comment]
That would match what HSPF does.

**Comment by rburghol** [comment]
This HSPF behavior is now mirrored in `hsp2`.  See #222 if interested in details.
