### ISSUE TITLE
HSPsquared model created from ./tests/land_spec/hwmA51800.uci fails with KeyError

### ISSUE THREAD

**Issue by timcera** [respec/HSPsquared#180]
`hsp2 import_uci ./tests/land_spec/hwmA51800.uci ./tests/land_spec/ref_run_hwmA51800.h5`
`hsp2 run ./tests/land_spec/ref_run_hwmA51800.h5`

fails with:

```
2024-10-02 22:48:40.71   Processing started for file ./tests/land_spec/ref_run_hwmA51800.h5; saveall=True
Traceback (most recent call last):
  File "/var/home/timcera/miniconda3/envs/default311/bin/hsp2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/HSP2_CLI.py", line 9, in main
    cltoolbox.main()
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 323, in __call__
    return self.execute(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 319, in execute
    return command(*real_args)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/commands.py", line 26, in run
    main(io_manager, saveall=saveall, jupyterlab=compress)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/main.py", line 119, in main
    state_om_model_run_prep(state, io_manager, siminfo)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om.py", line 202, in state_om_model_run_prep
    state_om_model_root_object(state, siminfo)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/om.py", line 194, in state_om_model_root_object
    for seg_name, seg_path in state["hsp_segments"].items():
                              ~~~~~^^^^^^^^^^^^^^^^
KeyError: 'hsp_segments'
```

**Comment by rburghol** [comment]
Thanks @timcera I will check this out asap.

**Comment by rburghol** [comment]
Hey @timcera I am just getting back to this, and independently, I am having some issues importing ucis with the latest versions of `hsp2`.  Question: what version of python is this occurring in?  I am not seeing this error in the automated tests, and am getting a *different* error myself `ValueError: The file 'ref_run_hwmA51800.h5' is already opened.  Please close it before reopening.  HDF5 v.1.8.5-patch1, FILE_OPEN_POLICY = 'strict'`
