### ISSUE TITLE
HSPsquared model created from ./tests/ipwater/data/HSPF_Test240.uci fails with AttributeError

### ISSUE THREAD

**Issue by timcera** [respec/HSPsquared#181]
`hsp2 import_uci ./tests/ipwater/data/HSPF_Test240.uci ./tests/ipwater/data/ref_run_HSPF_Test240.h5`
`hsp2 run ./tests/ipwater/data/ref_run_HSPF_Test240.h5`

failed with

```
2024-10-02 22:48:46.01   Processing started for file ./tests/ipwater/data/ref_run_HSPF_Test240.h5; saveall=True
2024-10-02 22:48:49.57   Simulation Start: 2018-01-01 00:00:00, Stop: 2019-01-01 00:00:00
2024-10-02 22:48:49.58      IMPLND I001 DELT(minutes): 60
Traceback (most recent call last):
  File "/var/home/timcera/miniconda3/envs/default311/bin/hsp2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/HSP2_CLI.py", line 9, in main
    cltoolbox.main()
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 323, in __call__
    return self.execute(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/miniconda3/envs/default311/lib/python3.11/site-packages/cltoolbox/cltoolbox.py", line 319, in execute
    return command(*real_args)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2tools/commands.py", line 26, in run
    main(io_manager, saveall=saveall, jupyterlab=compress)
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/main.py", line 168, in main
    ts = get_timeseries(
         ^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/utilities.py", line 421, in get_timeseries
    t = transform(data_frame, row.TMEMN, row.TRAN, siminfo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/timcera/programming/HSPsquared/src/hsp2/hsp2/utilities.py", line 217, in transform
    tsfreq = ts.index.freq
             ^^^^^^^^^^^^^
AttributeError: 'RangeIndex' object has no attribute 'freq'
```

**Comment by rburghol** [comment]
Hey @timcera -- I just ran back across this issue and tested it with the latest `develop` branch and this error no longer occurs.  I recall seeing this somewhere in the past and either I or @PaulDudaRESPEC fixed this (or maybe you!!!) I cannot recall, so I recommend closing this - I am unable to do so on this repo.
